version: 0.0
os: linux
files:
files:
  - source: scripts/*
    destination: /var/www/nextjsproject/scripts
  - source: appspec.yml
    destination: /var/www/nextjsproject
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      

