version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nextjsproject
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/cleanup.sh  # Cleanup ONLY here
      timeout: 300
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root  
  AfterInstall:                      # Install deps AFTER files are copied
    - location: scripts/install_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
