version: 0.0
os: linux
files:
  - source: scripts/start_server.sh
    destination: /var/www/nextjsproject/scripts/start_server.sh
  - source: scripts/stop_server.sh
    destination: /var/www/nextjsproject/scripts/stop_server.sh
  - source: scripts/install_dependencies.sh
    destination: /var/www/nextjsproject/scripts/install_dependencies.sh
  - source: appspec.yml
    destination: /var/www/nextjsproject
hooks:
  BeforeInstall:
    - location: /var/www/nextjsproject/scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: /var/www/nextjsproject/scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: /var/www/nextjsproject/scripts/stop_server.sh
      timeout: 300
