version: 0.0
os: linux
files:
  - source: scripts/startserver.sh
    destination: /var/www/nextjsproject/scripts/startserver.sh
  - source: scripts/stopserver.sh
    destination: /var/www/nextjsproject/scripts/stopserver.sh
  - source: scripts/install_dependencies.sh
    destination: /var/www/nextjsproject/scripts/install_dependencies.sh
  - source: appspec.yml
    destination: /var/www/nextjsproject
hooks:
  BeforeInstall:
    - location: /var/www/nextjsproject/scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: /var/www/nextjsproject/scripts/startserver.sh
      timeout: 300
  ApplicationStop:
    - location: /var/www/nextjsproject/scripts/stopserver.sh
      timeout: 300
