version: 0.2
phases:
  install:
    commands:
      - echo "Fetching fresh CodeArtifact authorization token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain my-domain --region ap-southeast-2 --query authorizationToken --output text)
      - echo "//my-domain-381491835701.d.codeartifact.ap-southeast-2.amazonaws.com/npm/my-npm-store/:_authToken=${CODEARTIFACT_AUTH_TOKEN}" > .npmrc
      - echo "Installing dependencies..."
      - npm install
  
  build:
    commands:
      - echo "Current directory:"
      - pwd
      - ls -la
      - ls -la src
      - ls -la src/styles
      - echo "Running build process..."
      - npm run build

  post_build:
    commands:
      - echo "Setting executable permissions..."
      - find scripts/ -name "*.sh" -exec chmod 755 {} \;
      - echo "Converting line endings..."
      - find scripts/ -name "*.sh" -exec dos2unix {} \;
      - echo "Verifying permissions..."
      - ls -la scripts/
      - echo "Cleaning sensitive files..."
      - rm -f .npmrc
      - echo "Listing contents of src/styles..."
      - ls -la src/styles
      - echo "Build completed successfully."

artifacts:
  files: 
    - appspec.yml
    - scripts/**
    - public/**
    - pages/**
    - src/**
    - package*.json
    - next.config.js
    - jsconfig.json
    - .npmrc  # Only include if needed for deployment
  discard-paths: no
  base-directory: testaws
