version: 0.2
phases:
  install:
    commands:
      - echo "Fetching fresh CodeArtifact authorization token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain my-domain --region ap-southeast-2 --query authorizationToken --output text)
      - echo "//my-domain-381491835701.d.codeartifact.ap-southeast-2.amazonaws.com/npm/my-npm-store/:_authToken=$CODEARTIFACT_AUTH_TOKEN" >> ~/.npmrc
      - echo "Installing dependencies..."
      - npm install
  
  build:
    commands:
      - echo "Running build process..."
      - npm run build

  post_build:
    commands:
      - echo "Setting executable permissions for deployment scripts..."
      - find scripts/ -name "*.sh" -exec chmod 755 {} \;
      - dos2unix scripts/*.sh
      - echo "Converting line endings for shell scripts..."
      - find scripts/ -name "*.sh" -exec dos2unix {} \;
      - echo "Build completed successfully."
      - echo "Cleaning up..."
      - rm -f ~/.npmrc

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - public/**/*
    - src/**/*
    - package*.json
    - next.config.mjs
  discard-paths: no
  base-directory: .
 
