version: 0.2

phases:
  install:
    commands:
      - echo "Fetching fresh CodeArtifact authorization token..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain my-domain --region ap-southeast-2 --query authorizationToken --output text)
      - echo "//my-domain-381491835701.d.codeartifact.ap-southeast-2.amazonaws.com/npm/my-npm-store/:_authToken=$CODEARTIFACT_AUTH_TOKEN" > ~/.npmrc
      - echo "Installing dependencies..."
      - npm install  

  build:
    commands:
      - echo "Running build process..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully."
      - echo "Zipping the deployment package..."
      - zip -r deployment-package.zip .  # Zips everything into deployment-package.zip
      - echo "Uploading to S3..."
      - aws s3 cp deployment-package.zip s3://nextjs-build-artifact-monkweb/deployment-package.zip
      - echo "Cleaning up..."
      - rm -f ~/.npmrc

artifacts:
  files:
    - '**/*'   # Includes all files in the build output
    - appspec.yml
    - scripts/**/*
  discard-paths: no
  base-directory: .  # Ensures the zip contains only necessary files
  name: deployment-package  # Creates deployment-package.zip


